# spring.application.name=producer
# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.consumer.group-id=myGroup

# Required connection configs for Kafka producer, consumer, and admin
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='GCELIAZMZVE3SGXO' password='cfltt6BnaMHb+2i73rZkkE8u7CADWuxeggQj0zkewuQCpFMlv/Lj/S0dwf2LeWAg';
spring.kafka.properties.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
spring.kafka.properties.session.timeout.ms=45000

client.id=ccloud-springboot-client-639fd0e6-5548-4231-8681-6a921b853b58